version: "3.9"
services:
  webserver:
    build: .
    command: sh -c "/docker-entrypoint.sh"
    environment:
      DJANGO_SETTINGS_MODULE: "deinplugin.prodsettings"
      DJANGO_DB_NAME: "django_db"
      DJANGO_DB_USER: "djangouser"
      DJANGO_DB_PASSWORD: "djangopass"
      DJANGO_DB_HOST: "django-db"
      DJANGO_DB_PORT: "5091"
      WAIT_HOSTS: "django-db:5091"
      WAIT_SLEEP_INTERVAL: "3"
      WAIT_TIMEOUT: "60"
    volumes:
      - ./logs/apache:/var/www/logs
      - ./apache-config.conf:/etc/apache2/sites-available/000-default.conf:ro
      - ./certs:/certs:ro
    depends_on:
      - django-db
    ports:
      - "5097:443"

  django-db:
    image: postgres:latest
    command: -p 5091
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: "django_db"
      POSTGRES_PASSWORD: "djangopass"
      POSTGRES_USER: "djangouser"
    volumes:
      - type: volume
        source: django-db-data
        target: /var/lib/postgresql/data/pgdata
        volume:
          nocopy: true
    ports:
      - "5091:5091"

volumes:
  django-db-data:
