# Generated by Django 4.1.3 on 2022-12-10 11:42

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plugin',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('specVersion', models.IntegerField(default=1)),
                ('type', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('plugin', 'Plugin'), ('lib', 'Lib')], default='plugin', max_length=100), size=None)),
                ('supportedPlatforms', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('spigot', 'Spigot'), ('paper', 'Paper'), ('sponge', 'Sponge')], max_length=100), blank=True, null=True, size=None)),
                ('supportedGameVersions', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None)),
                ('category', models.CharField(max_length=100)),
                ('authors', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, null=True, size=None)),
                ('images', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, null=True, size=None)),
                ('icon', models.CharField(max_length=100)),
                ('videoSources', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, null=True, size=None)),
                ('version', models.CharField(max_length=100)),
                ('github_url', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Introduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=5)),
                ('value', models.TextField()),
                ('plugin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.plugin')),
            ],
        ),
        migrations.CreateModel(
            name='Installation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=5)),
                ('value', models.TextField()),
                ('plugin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.plugin')),
            ],
        ),
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=5)),
                ('value', models.TextField()),
                ('plugin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.plugin')),
            ],
        ),
        migrations.CreateModel(
            name='Dependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=100)),
                ('versionRange', models.CharField(max_length=100)),
                ('required', models.BooleanField(default=True)),
                ('plugin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.plugin')),
            ],
        ),
    ]
