# Generated by Django 4.1.2 on 2022-12-10 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plugin',
            name='type',
            field=models.CharField(choices=[('plugin', 'Plugin'), ('lib', 'Lib')], default='plugin', max_length=100),
        ),
    ]
