# Generated by Django 4.1.2 on 2022-12-10 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_plugin_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plugin',
            name='version',
        ),
    ]
