# Generated by Django 4.1.2 on 2022-12-10 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_plugin_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plugin',
            name='supportedGameVersions',
            field=models.CharField(max_length=100),
        ),
    ]
