# Generated by Django 4.1.2 on 2022-12-10 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_plugin_supportedgameversions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plugin',
            name='name',
        ),
        migrations.AlterField(
            model_name='dependency',
            name='plugin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencies', to='main.plugin'),
        ),
        migrations.AlterField(
            model_name='description',
            name='plugin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descriptions', to='main.plugin'),
        ),
        migrations.AlterField(
            model_name='installation',
            name='plugin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installations', to='main.plugin'),
        ),
        migrations.AlterField(
            model_name='introduction',
            name='plugin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='introductions', to='main.plugin'),
        ),
        migrations.CreateModel(
            name='PluginName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=5)),
                ('value', models.CharField(max_length=100)),
                ('plugin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='names', to='main.plugin')),
            ],
        ),
    ]
