# Generated by Django 4.1.2 on 2022-12-10 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_plugin_name_alter_dependency_plugin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='description',
            name='key',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='installation',
            name='key',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='introduction',
            name='key',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='pluginname',
            name='key',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
