# Generated by Django 4.1.2 on 2022-12-10 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_description_key_alter_installation_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plugin',
            name='icon',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
