# Generated by Django 4.1.2 on 2022-12-18 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_plugin_state_alter_plugin_github_url_download'),
    ]

    operations = [
        migrations.RenameField(
            model_name='download',
            old_name='url',
            new_name='download_url',
        ),
    ]
