# Generated by Django 4.1.2 on 2022-12-20 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_plugin_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plugin',
            name='mail',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
