# Generated by Django 4.1.2 on 2022-12-21 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_plugin_mail'),
    ]

    operations = [
        migrations.AddField(
            model_name='plugin',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='plugin',
            name='last_yaml_hash',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='plugin',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
